# 2.3 Numpy 基礎(三) 常用陣列產生函數


## arange

###      語法  np.arange( 起始值, 結束值, 步幅, 資料型別 )：

    產生一維陣列，和np.array()的差別在於arange擁有較大的彈性，而且元素數值是自動化產生！

    步幅可為小數，決定每隔多少數值產生一個元素。

In [1]:
import numpy as np
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

## linspace

### 語法  np.linspace( 起始值, 結束值, 起始與結束的區間內要產生幾個元素 )：

    只要給定陣列的區間(起始值、結束值)，就可以要求在這個區間內產生幾個元素！

In [ ]:
np.linspace(0,5,10,endpoint=True)

## Zeros

### 語法 np.zeros( (陣列各維度大小用逗號區分) )：

    建立全為0的陣列，可以小括號定義陣列的各個維度的大小！

In [3]:
a = np.zeros(10)
b = np.zeros([4,6])
print(a,"\n",b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Ones

### 語法: np.ones( (陣列各維度大小用逗號區分) )：

    建立全為1的陣列，可以小括號定義陣列的各個維度的大小！用法與np.zeros一樣！



In [ ]:
np.ones([3,5])

## Empty

### 語法: np.empty( (陣列各維度大小用逗號區分) )：

    用法與np.zeros一樣，但唯一的差別是NumPy不會初始化陣列內元素的初始值，所以內容將會是不確定的。

In [2]:
import numpy as np
np.empty(100)

array([ 8.88968985e+228,  1.42553124e+248,  3.00966884e-153,
        3.62485156e+228,  1.69375267e+190,  1.41434688e+190,
        7.50187034e+247,  6.13500841e-095,  6.01334635e-154,
        3.55414903e+246,  9.13600552e+242,  4.53579889e+217,
        2.98365018e+174,  1.69374419e+190,  1.27734658e-152,
        1.11493683e+277,  2.34840919e+251,  3.04284970e+169,
        9.09157492e+223, -7.13105183e-311,  1.67792004e+243,
        3.62481984e+228,  1.22606275e-259,  9.23546148e+242,
        2.52960802e-258,  4.47593804e-091,  2.44041296e-154,
        2.05916629e-115,  1.05540265e-153,  4.83245960e+276,
        6.01347002e-154,  9.76515186e+199,  4.70107595e+180,
        3.81595085e+180,  3.99255543e+252,  1.68823157e+195,
        3.03585034e+180,  2.31463017e-152,  6.01346953e-154,
        3.03585034e+180,  1.28898628e+248,  1.87673448e-152,
        4.93318357e+257,  6.01334515e-154,  1.94858176e-153,
        1.61861269e+102,  9.77824555e+199,  6.01334653e-154,
        4.23372712e+180,

## random.random 均勻分佈亂數


<img align="center" style="padding-right:10px;" src="figures\uniform_distribution.gif">

### 語法: np.random.random(陣列各維度大小用逗號區分)

    產生指定數量介於0~1 均勻分佈的浮點數



In [ ]:
np.random.random(100)

## random.normal  標準(正態，高斯)分佈亂數

### 語法: np.random.normal(loc=0.0, scale=1.0, size=None)

$loc=\mu 是平均值$

$scale=\sigma 為標準差$

<img align="center" style="padding-right:10px;" src="figures\normal_distribution.png">
<img align="center" style="padding-right:10px;" src="figures\normal_distribution2.png">


In [ ]:
np.random.normal(0,1,100)

## 數據資料的直線圖

In [ ]:
import matplotlib.pyplot as plt
w=np.random.random(500)
z=np.random.normal(0.5,0.2,500)
fig,ax=plt.subplots(ncols=2,figsize=(12,6))
ax[0].plot(w)
ax[1].plot(z)

## 直方圖 histogram -- 數據出現頻率分佈圖

    

### 語法 hist(x, bin=10)

    x: 串列資料
    bin: 水平尺寸相等矩形個數

In [ ]:
import matplotlib.pyplot as plt
w=np.random.random(5000)
z=np.random.normal(0.5,0.2,5000)
fig,ax=plt.subplots(ncols=2,figsize=(12,6))
ax[0].hist(w,bins=50)
ax[1].hist(z,bins=50)

## 練習

修改下例，產生

1、介於10~100的均勻分佈

2、平均值為60，標準差為10的標準分佈

In [ ]:
import matplotlib.pyplot as plt
w=np.random.random(5000)
z=np.random.normal(0,1,5000)
fig,ax=plt.subplots(ncols=2,figsize=(12,6))
ax[0].hist(w,bins=50)
ax[1].hist(z,bins=50)

## np.full 

### 語法 np.full(shape, fill_value, dtype=None)

    產生指定值陣列的函數


In [5]:
np.full((5,6),1)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## np.eye

### 語法 np.eye(N, M=None)

### 產生單位矩陣


In [9]:
print(np.eye(4))
print(np.eye(4,2))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]


# 變更陣列形狀的函數

## ravel: 壓平陣列成為一維陣列
## reshape: 產生不同形狀的陣列，但資料維持一致
## resize: 改變陣列形狀，但資料維持一致

In [15]:
a = np.arange(0,10)
print('a:',a)
b=a.reshape(2,5)
print('b:',b)
print('a:',a)
c=b.ravel()
print('c:',c)

a: [0 1 2 3 4 5 6 7 8 9]
b: [[0 1 2 3 4]
 [5 6 7 8 9]]
a: [0 1 2 3 4 5 6 7 8 9]
c: [0 1 2 3 4 5 6 7 8 9]


In [24]:
a = np.arange(0,10)
print('a',a)
a.resize(2,5)
print('a',a)

a [0 1 2 3 4 5 6 7 8 9]
a [[0 1 2 3 4]
 [5 6 7 8 9]]


## 練習: 產生下列資料  
    [[ 1  2  3  4  5  6  7  8  9 10 11 12]  
     [13 14 15 16 17 18 19 20 21 22 23 24]  
     [25 26 27 28 29 30 31 32 33 34 35 36]  
     [37 38 39 40 41 42 43 44 45 46 47 48]  
     [49 50 51 52 53 54 55 56 57 58 59 60]  
     [61 62 63 64 65 66 67 68 69 70 71 72]  
     [73 74 75 76 77 78 79 80 81 82 83 84]  
     [85 86 87 88 89 90 91 92 93 94 95 96]]  